[project]
name = "bus-location-service-tesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beanie>=1.27.0",
    "fastapi[all]>=0.115.5",
    "geopy>=2.4.1",
    "python-dotenv>=1.0.1",
]
